feature/a star escape
djv3/CSM100-temple-of-gloom pull request #5
Opened 2023-07-07 05:39 UTC by djv3

This PR implements the A star search algorithm for the escape phase, along with a base heuristic interface (currently an abstract class) from which other heuristics can be implemented. I've implemented a greedier heuristic which considers the amount of gold on a tile when calculating the best path to the exit, so whilst still probably too efficient it does see an increase in score over what we're getting on the main branch currently.

Currently on main branch when running `gradle run --args='-s -4152836868077314850 -n 10'`
```
Seed : -4152836868077314850
Gold collected   : 12814
Bonus multiplier : 1.07
Score            : 13729

Average score : 14160
```

When the same is run on this branch:
```
Seed : -4152836868077314850
Gold collected   : 14914
Bonus multiplier : 1.07
Score            : 15979

Average score : 16481
```

2023-07-07 08:51 UTC, alc25-london-ac-uk requested changes

2023-07-07 08:51 UTC, alc25-london-ac-uk commented on temple/src/main/java/student/GreedyHeuristic.java
> +        int exitColumn = node.getTile().getColumn();
Shouldn't this be exitNode.getTile().getColumn()?

2023-07-07 08:51 UTC, alc25-london-ac-uk commented on temple/src/main/java/student/GreedyHeuristic.java
> +        int exitRow = node.getTile().getRow();
Shouldn't this be exitNode.getTile().getRow()?

2023-07-08 13:33 UTC, alc25-london-ac-uk approved these changes

2023-07-08 13:35 UTC, djv3 commented on temple/src/main/java/student/GreedyHeuristic.java
> +        int exitColumn = node.getTile().getColumn();
Good catch on these, have fixed and will resolve

2023-07-08 13:36 UTC, merged